site_name: ERRONKA 3
theme:
  name: material
  palette: 
    # Light/Dark mode toggle!
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# This adds a nice search bar and navigation
#features:
#  - navigation.tabs
#  - search.suggest
#  - search.highlight
# Add this section:
nav:
  - Home: index.md
  - About: about.md
  - Page3: page3.md
  - Page4: page4.md
  - Gallery: gallery.md